# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemesSiteBuilder#theme-configuration for an example

name = "Hugo Feeds"
license = "MIT"
licenselink = "https://codeberg.org/yelosan/hugo-feeds/src/branch/main/LICENSE"
description = "Hugo theme component for creating ATOM and RSS feeds."

# The home page of the theme, where the source can be found.
homepage = "https://codeberg.org/yelosan/hugo-feeds"

# If you have a running demo of the theme.
#demosite = "https://gohugo.io"

tags = ["component", "feed", "atom", "rss", "rss2", "output-format"]
features = ["atom", "rss"]

# If the theme has multiple authors
#authors = [
#  {name = "Name of author", homepage = "Website of author"},
#  {name = "Name of author", homepage = "Website of author"}
#]

# If the theme has a single author
[author]
  name = "techmagus ― I'M YourOnly.One"
  homepage = "https://youronly.one"

# If porting an existing theme
[original]
  author = "Kaushal Modi"
  homepage = "https://scripter.co"
  repo = "https://github.com/kaushalmodi/hugo-atom-feed/"
